### ISSUE TITLE
[Feature Request] support C library for LAMMPS

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#2236]
### Summary

Support C library for LAMMPS.

### Detailed Description

There are some APIs not implemented yet:

- [x] fparam, aparam
  - [x] `DeepPot` #2415
  - [x] `DeepPotModelDevi` #2486
  - [x] add tests for them #2351
- [x] `deepmd::select_by_type` #2491
  - [x] add tests #2337
- [x] `deepmd::select_map` #2491
  - [x] add tests #2338
- [x] `deepmd::read_file_to_string` #2412
  - [x] add tests #2338
- [x] `deepmd::deepmd_exception` #2344
  - [x] add tests #2338
- [x] `deep_pot_model_devi` stats
  - [x] `deep_pot_model_devi.compute_avg` (no energy) #2493
  - [x] `deep_pot_model_devi.compute_std` #2493
  - [x] <del>`deep_pot_model_devi.compute_std_e`</del> removed in #2492
  - [x] `deep_pot_model_devi.compute_std_f` #2493
  - [x] `deep_pot_model_devi.compute_relative_std` #2493
  - [x] `deep_pot_model_devi.compute_relative_std_f` #2493

After resolving all the above, we can support the C API for LAMMPS.
- [ ] support C API for LAMMPS
  - [x] add tests for `compute deeptensor/atom` #2507
  - [ ] add tests for `kspace_style pppm/dplr`
