### ISSUE TITLE
[Feature Request] support TF 2.12

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#2331]
### Summary

Here is a checklist to support TF 2.12.

### Detailed Description

For 2.12.0rc0:
- [x] fix version detection of release candidate version #2332
- [x] `.dylib` file was removed from macOS wheels with only `.2.dylib` left #2333
- [x] `libtensorflow_cc` library is now available inside wheels per https://github.com/tensorflow/tensorflow/pull/55941. Remove the dependency on `_pywrap_tensorflow_internal` and removes the dependency on libpython (cmake, lammps) #2335
  - [x] migrate C++ workflows #2422
  - [x] update documentation #2422
- [x] TF 2.12 adds Python 3.11 supports and drops Python 3.7 supports, test TF 2.12 on Python 3.11 #2422
