### ISSUE TITLE
[Feature Request] Merge CUDA and ROCm codes

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#2838]
### Summary

Merge CUDA and ROCm codes into one file and distinguish them using macros.

### Detailed Description

There are lots of duplicated codes between CUDA and ROCm. Most of them are the same. Adding a new GPU method is troublesome as we need to add twice to both CUDA and ROCm codes.
I notice that TensorFlow implements CUDA and ROCm in only one file, such as https://github.com/tensorflow/tensorflow/blob/00a17d7451a789a4df994dac7d616ce2f4438ff0/tensorflow/core/kernels/relu_op_gpu.cu.cc#L16. Some different codes between them are controlled using macros, i.e., `GOOGLE_CUDA` and `TENSORFLOW_USE_ROCM`. A universal launch function, `GpuLaunchKernel`, is used for CUDA and ROCm.

Below is the roadmap for DeePMD-kit:
- [x] Migrate to universal functions for CUDA and ROCM created in `gpu_cuda.h` and `gpu_rocm.h` #2844
- [x] Make the method have the same name between CUDA and ROCM, i.e., no `_rocm` suffix anymore #2839
- [x] Clean the duplicated codes and use `GOOGLE_CUDA || TENSORFLOW_USE_ROCM` for the same code
  - [x] `lib/cuda` and `lib/rocm` #2844
  - [x] `op` #2847
  - [x] `lib/tests` #2846
  - [x] `lib/include` #2845
