### ISSUE TITLE
[Feature Request] add unit tests

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#838]
**Summary**

Add unit tests for the following methods or classes.

**Detailed Description**

- [x] deepmd.cluster.slurm.get_resource
- [x] deepmd.cluster.slurm._pad_zeros #913
- [x] deepmd.cluster.slurm._expand_ids #913
- [x] deepmd.cluster.slurm._expand_nodelist #913
- [x] deepmd.descriptor.hybrid.DescrptHybrid #2611
- [x] deepmd.descriptor.se_a_ebd.DescrptSeAEbd #2353
- [ ] deepmd.descriptor.se_a_ef.DescrptSeAEf
- [x] <del>deepmd.entrypoints.config.valid_dir</del>
- [x] <del>deepmd.entrypoints.config.load_systems</del>
- [x] <del>deepmd.entrypoints.config.get_system_names</del>
- [x] <del>deepmd.entrypoints.config.get_rcut</del>
- [x] <del>deepmd.entrypoints.config.get_batch_size_rule</del>
- [x] <del>deepmd.entrypoints.config.get_stop_batch</del>
- [x] <del>deepmd.entrypoints.config.get_ntypes</del>
- [x] <del>deepmd.entrypoints.config.get_max_density</del>
- [x] <del>deepmd.entrypoints.config.suggest_sel</del>
- [x] <del>deepmd.entrypoints.config.suggest_batch_size</del>
- [x] <del>deepmd.entrypoints.config.suggest_decay</del>
- [x] <del>deepmd.entrypoints.config.config</del>
- [x] deepmd.entrypoints.convert.convert #2175
- [ ] deepmd.entrypoints.doc.doc_train_input
- [x] deepmd.entrypoints.test.test #2785
- [x] deepmd.entrypoints.test.rmse #2785
- [x] deepmd.entrypoints.test.save_txt_file #2785
- [x] deepmd.entrypoints.test.test_ener #2785
- [x] deepmd.entrypoints.test.print_ener_sys_avg #2785
- [x] deepmd.entrypoints.test.run_test #2785
- [ ] deepmd.entrypoints.test.test_wfc
- [ ] deepmd.entrypoints.test.print_wfc_sys_avg
- [x] deepmd.entrypoints.test.test_polar #2785
- [ ] deepmd.entrypoints.test.print_polar_sys_avg
- [x] deepmd.entrypoints.test.test_dipole #2785
- [ ] deepmd.entrypoints.test.print_dipole_sys_avg
- [x] <del>deepmd.entrypoints.train.create_done_queue</del>
- [x] <del>deepmd.entrypoints.train.wait_done_queue</del>
- [x] <del>deepmd.entrypoints.train.connect_done_queue</del>
- [x] <del>deepmd.entrypoints.train.fill_done_queue</del>
- [x] deepmd.entrypoints.train.get_rcut
- [x] deepmd.entrypoints.train.get_type_map
- [x] deepmd.entrypoints.train.get_sel
- [ ] deepmd.entrypoints.transfer.convert_number
- [ ] deepmd.entrypoints.transfer.convert_matrix
- [x] <del>deepmd.fit.polar.PolarFittingLocFrame</del> (removed in #2140)
- [ ] deepmd.infer.deep_polar.DeepGlobalPolar
- [ ] deepmd.infer.deep_wfc.DeepWFC
- [x] deepmd.infer.model_devi.calc_model_devi_e
- [ ] deepmd.infer.model_devi._check_tmaps
- [x] deepmd.infer.model_devi.make_model_devi #2433
- [x] deepmd.loggers.loggers._MPIRankFilter
- [ ] deepmd.loggers.loggers._MPIFileStream
- [ ] deepmd.loggers.loggers._MPIHandler
- [ ] deepmd.loss.ener.EnerDipoleLoss 
- [ ] deepmd.utils.compat._warning_input_v0_v1
- [ ] deepmd.utils.compat._warning_input_v1_v2
- [ ] deepmd.utils.convert.convert_13_to_20
- [ ] deepmd.utils.convert.convert_12_to_20
- [x] deepmd.utils.convert.convert_pb_to_pbtxt #2175
- [x] deepmd.utils.convert.convert_pbtxt_to_pb #2175
- [x] deepmd.utils.convert.convert_dp12_to_dp13 #2175
- [x] deepmd.utils.convert.convert_dp13_to_dp20 #2175
- [x] deepmd.utils.weight_avg.weighted_average #2785

**Comment by shishaochen** [comment]
These 3 functions seems have problem to write unit tests for 100% code coverage.
- [ ]  deepmd.cluster.slurm._pad_zeros
- [ ]  deepmd.cluster.slurm._expand_ids
- [ ]  deepmd.cluster.slurm._expand_nodelist

One reason is that both `_expand_nodelist` and `_expand_ids` use commas to separate tokens. Considering execution order, the function `_expand_ids` has no chance to handle id string with any comma.

@denghuilu Do you have any document on the schema of the environment variable `SLURM_JOB_NODELIST`?

**Comment by denghuilu** [comment]
> While improvement comes in #913, these 3 functions seems have problem in unit tests for 100% code coverage.
> 
> * [ ]   deepmd.cluster.slurm._pad_zeros
> * [ ]   deepmd.cluster.slurm._expand_ids
> * [ ]   deepmd.cluster.slurm._expand_nodelist
> 
> One reason is that both `_expand_nodelist` and `_expand_ids` use commas to separate tokens. Considering execution order, function `_expand_ids` has no chance to handle argument `ids` with any comma. Consequently, function `_pad_zeros` will never be called.
> 
> @denghuilu Do you have any document on the schema of environment variable `SLURM_JOB_NODELIST`? Maybe we can write a better parsing logic. All I can find is [Slurm Environmental Variables](https://hpcc.umd.edu/hpcc/help/slurmenv.html) and [slurm.h.in](https://github.com/SchedMD/slurm/blob/master/slurm/slurm.h.in#L1168).

I also found the possible definition at https://hpcc.umd.edu/hpcc/help/slurmenv.html. @amcadmus Any suggestions?

**Comment by njzjz** [comment]
See here: https://slurm.schedmd.com/faq.html

**Comment by shishaochen** [comment]
@njzjz @denghuilu The package [python-hostlist](https://www.nsc.liu.se/~kent/python-hostlist/) seems professional.

Now code coverages on both `deepmd.cluster.local` and `deepmd.cluster.slurm` reach 100%.

**Comment by njzjz** [comment]
Close since most of the tasks have been done.
